### ISSUE TITLE
использование вместе с zapret

### ISSUE THREAD

**Issue by labi-le** [itdoginfo/domain-routing-openwrt#11]
можно ли использовать этот скрипт совместно с [zapret](https://github.com/bol-van/zapret), если да, то как?
у меня возникали конфликты, роутинг доменов из списка не работал

**Comment by itdoginfo** [comment]
Этот скрипт настраивает очень примитивную логику, использование других инструментов в него не закладывалось. Но в будущем это будет. Как сейчас это реализовать лучше спросить в чате.
