### ISSUE TITLE
Заменить wireguard на amneziawg

### ISSUE THREAD

**Issue by w0rng** [itdoginfo/domain-routing-openwrt#12]
Предлагаю заменить wireguard на amnezia-wg, так как первый легко блокируется dpi и смысла от него нынче никакого. AmneziaWG умеет в обфускацию трафика и полностью совместима с wireguard. 

https://github.com/itdoginfo/domain-routing-openwrt/blob/aae9c50f10dee2e51800c8742a62ce87eecadc3c/getdomains-install.sh#L44

**Comment by DimiDr0l** [comment]
@w0rng предлагаю скинуть ПР)

**Comment by w0rng** [comment]
> @w0rng предлагаю скинуть ПР)

Я бы с радостью, но на руках пока что нет устройств с openwrt. Через неделю должен роутер приехать, могу заняться)

**Comment by w0rng** [comment]
похоже, amneziawg-tool до сих пор не добавили в официальный реестр пакетов. Тогда все эта затея не кажется хорошей, кто сможет установить этот пакет, сможет и все остальное настроить. 

https://github.com/openwrt/packages/pull/23633

**Comment by itdoginfo** [comment]
@w0rng
1. > смысла от него нынче никакого
Это утверждение неверно. Рекомендую не доверять паническим сообщениям в интернете, а лично проверять, что работает, что нет.

2. AWG не то что в репах OpenWrt отсутствует, у него бинарников даже нет для разных архитектур. Поэтому, прежде чем делать какую-либо автоматизацию его установки, надо разобраться с этим.

**Comment by w0rng** [comment]
@itdoginfo 

> Это утверждение неверно. Рекомендую не доверять паническим сообщениям в интернете, а лично проверять, что работает, что нет.

Лично попал блокировки в прошлом году, было неприятно и повторения не хочется. А с учетом того, что в моем регионе, судя по всему, любят тестировать новые ограничения, это может повториться вновь. 

>  Поэтому, прежде чем делать какую-либо автоматизацию его установки, надо разобраться с этим.

Да, соглашусь. Посему предлагаю закрыть данное обсуждение до лучших времен

**Comment by w0rng** [comment]
ого, открыли PR на добавление awg, так еще и инструкцию по сборке приложили. @Slava-Shchipunov спасибо!!

https://github.com/itdoginfo/domain-routing-openwrt/pull/13
