### ISSUE TITLE
OpenWRT 24

### ISSUE THREAD

**Issue by fildunsky** [itdoginfo/domain-routing-openwrt#14]
Огромная просьба, добавить поддержку снапшотов OpenWRT 24. Вручную менял настройки скрипта, чтобы он выдавал значение 23 вместо 24 на моём GL-MT3000 всё сработало.

**Comment by itdoginfo** [comment]
24ой верии ещё нет даже в RC. Для GL-MT3000 есть стабилка, используйте её.
